# Generated by Django 4.2.3 on 2024-06-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason_id', models.IntegerField()),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancellation_type', models.CharField(blank=True, max_length=255)),
                ('cancelled_after_ship', models.BooleanField()),
                ('affect_cancellation_rating', models.BooleanField()),
                ('cancellation_initiator', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('warehouse_id', models.BigIntegerField()),
                ('warehouse', models.CharField(max_length=255)),
                ('tpl_provider_id', models.IntegerField()),
                ('tpl_provider', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('offer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('mandatory_mark', models.JSONField()),
                ('currency_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_requiring_gtd', models.JSONField()),
                ('products_requiring_country', models.JSONField()),
                ('products_requiring_mandatory_mark', models.JSONField()),
                ('products_requiring_rnpt', models.JSONField()),
                ('products_requiring_jw_uin', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_number', models.CharField(max_length=100)),
                ('order_id', models.BigIntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('tpl_integration_type', models.CharField(max_length=100)),
                ('in_process_at', models.DateTimeField()),
                ('shipment_date', models.DateTimeField()),
                ('delivering_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.JSONField(blank=True, null=True)),
                ('addressee', models.JSONField(blank=True, null=True)),
                ('barcodes', models.JSONField(blank=True, null=True)),
                ('analytics_data', models.JSONField(blank=True, null=True)),
                ('financial_data', models.JSONField(blank=True, null=True)),
                ('is_express', models.BooleanField()),
                ('parent_posting_number', models.CharField(blank=True, max_length=100)),
                ('available_actions', models.JSONField()),
                ('multi_box_qty', models.IntegerField()),
                ('is_multibox', models.BooleanField()),
                ('substatus', models.CharField(max_length=100)),
                ('prr_option', models.CharField(blank=True, max_length=100)),
                ('quantum_id', models.IntegerField()),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.cancellation')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.deliverymethod')),
                ('products', models.ManyToManyField(to='drf.product')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.requirement')),
            ],
        ),
    ]
